2_lesson
Skala15/Js_base pull request #4
Opened 2020-07-20 09:03 UTC by Skala15

2020-07-22 20:39 UTC, HaseProgram requested changes
Хорошая работа, но есть пара моментов, которые можно доработать. Допишите 4 задание, а также подумайте над рекурсией :)

2020-07-22 20:39 UTC, HaseProgram commented on Lesson_2/script/lesson_2.js
> +switch (a) {
Смотрите. Чем отличается эти 2 блока с кодом
```JavaScript
const a  = 1;
switch (a) {
  case 1:
    console.log('1');
    break;
  case 2:
    console.log('2');
    break;
}
```
и
```JavaScript
const a  = 1;
switch (a) {
  case 1:
    console.log('1');
  case 2:
    console.log('2');
}
```

Из этих примеров, думаю, должно быть понятно, что имелось в виду в задании, а также как его делать :)

2020-07-22 20:39 UTC, HaseProgram commented on Lesson_2/script/lesson_2.js
> +function mathOperation() {
Собственно функция вполне себе работоспособная. Только вы забыли ее вызвать :)
Чтобы функция отработала, ее необходимо заставить исполниться:
```JavaScript
// код функции ниже
function doSomething () {
  console.log('Hello!');
}

// вызов функции ниже
doSomething();
```

2020-07-22 20:39 UTC, HaseProgram commented on Lesson_2/script/lesson_2.js
> +alert(a == b)      //false так как null - это объект, а 0 - это число, то сравнить их нельзя и получается false (я так понял)
Ответ правильный, но почему именно так - на самом деле немного интереснее)
Можно об этом почитать об этом в данной статье: https://habr.com/ru/company/ruvds/blog/337732/

2020-07-22 20:39 UTC, HaseProgram commented on Lesson_2/script/lesson_2.js
> +function power(val, pow) {
Это выдаст правильный ответ, но это не рекурсия :)
Если не очень понятно, как работать с рекурсией, могу посоветовать данную статью: https://habr.com/ru/post/337030/

Попробуйте решить, и пришлите мне результат. Если будут проблемы - пишите)

2020-07-28 13:30 UTC, Skala15 commented
Точнее четвертое задание второго урока переделано

2020-07-31 19:54 UTC, closed without merging